;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Inventory.Fragments.Usable.Potions.Blue.Big",NewTagName="Inventory.Fragments.Usable.Potions.Blue.Large")
+GameplayTagList=(Tag="Inventory.Fragments.Usable.Potions",DevComment="")
+GameplayTagList=(Tag="Inventory.Fragments.Usable.Potions.Blue",DevComment="")
+GameplayTagList=(Tag="Inventory.Fragments.Usable.Potions.Blue.Large",DevComment="")
+GameplayTagList=(Tag="Inventory.Fragments.Usable.Potions.Blue.Small",DevComment="")
+GameplayTagList=(Tag="Inventory.Fragments.Usable.Potions.Red",DevComment="")
+GameplayTagList=(Tag="Inventory.Fragments.Usable.Potions.Red.Large",DevComment="")
+GameplayTagList=(Tag="Inventory.Fragments.Usable.Potions.Red.Small",DevComment="")

